apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: hello-world-2
  namespace: '723641240714'
  selfLink: /apis/serving.knative.dev/v1/namespaces/723641240714/services/hello-world-2
  uid: c1550cb6-b5fe-443a-8259-8fafa800699f
  resourceVersion: AAXz56U//ZI
  generation: 2
  creationTimestamp: '2023-02-04T22:32:08.646505Z'
  labels:
    managed-by: gcp-cloud-build-deploy-cloud-run
    gcb-trigger-id: 376b4046-a9e1-40ff-a7d6-055be7174282
    cloud.googleapis.com/location: us-central1
  annotations:
    run.googleapis.com/client-name: cloud-console
    serving.knative.dev/creator: dfrankle2@gmail.com
    serving.knative.dev/lastModifier: dfrankle2@gmail.com
    client.knative.dev/user-image: gcr.io/zippy-chariot-351820/hello-world-1:latest
    run.googleapis.com/operation-id: 597dc446-d2cb-4cc3-97fe-aa171b0db250
    run.googleapis.com/ingress: all
    run.googleapis.com/ingress-status: all
spec:
  template:
    metadata:
      name: hello-world-2-00001-pov
      annotations:
        run.googleapis.com/client-name: cloud-console
        autoscaling.knative.dev/maxScale: '100'
    spec:
      containerConcurrency: 80
      timeoutSeconds: 300
      serviceAccountName: 723641240714-compute@developer.gserviceaccount.com
      containers:
      - image: gcr.io/zippy-chariot-351820/hello-world-1:latest
        ports:
        - name: http1
          containerPort: 8080
        resources:
          limits:
            cpu: 1000m
            memory: 512Mi
  traffic:
  - percent: 100
    latestRevision: true
status:
  observedGeneration: 2
  conditions:
  - type: Ready
    status: 'True'
    lastTransitionTime: '2023-02-04T22:32:21.872497Z'
  - type: ConfigurationsReady
    status: 'True'
    lastTransitionTime: '2023-02-04T22:32:20.685029Z'
  - type: RoutesReady
    status: 'True'
    lastTransitionTime: '2023-02-04T22:32:21.872497Z'
  latestReadyRevisionName: hello-world-2-00001-pov
  latestCreatedRevisionName: hello-world-2-00001-pov
  traffic:
  - revisionName: hello-world-2-00001-pov
    percent: 100
    latestRevision: true
  url: https://hello-world-2-uwtxkaaejq-uc.a.run.app
  address:
    url: https://hello-world-2-uwtxkaaejq-uc.a.run.app
